[package]
name = "cvldoc_parser_core"
version = "0.5.0"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
chumsky = { git = "https://github.com/zesterer/chumsky", branch = "master" }
clap = { version = "4.0.22", features = ["cargo", "derive"] }
color-eyre = "0.6.2"
indoc = "1.0.7"
itertools = "0.10.5"
lsp-types = "0.93.2"
once_cell = "1.16.0"
regex = "1.7.0"
ropey = "1.5.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tap = "1.0.1"
