[package]
name = "natspec_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { git = "https://github.com/zesterer/chumsky" }
clap = { version = "3.2.15", features = ["cargo", "derive"] }
color-eyre = "0.6.2"
indoc = "1.0.6"
itertools = "0.10.3"
lsp-types = "0.93.0"
ropey = "1.5.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
tap = "1.0.1"
