[package]
name = "natspec_parser"
version = "0.3.0"
edition = "2021"

[dependencies]
assert_matches = "1.5.0"
chumsky = { git = "https://github.com/zesterer/chumsky" }
clap = { version = "3.2.17", features = ["cargo", "derive"] }
color-eyre = "0.6.2"
indoc = "1.0.7"
itertools = "0.10.3"
lsp-types = "0.93.0"
once_cell = "1.13.1"
regex = "1.6.0"
ropey = "1.5.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tap = "1.0.1"
