version: 2.1
jobs:
  build-the-package:
    docker:
      - image: messense/manylinux2014-cross:x86_64
    steps:
      - checkout
      - run:
          name: "APT Install Dependencies"
          command: |
              sudo apt-get update
              sudo apt-get install curl
      - run:
          name: "Install Rust"
          command: |
              curl "https://sh.rustup.rs" -o "rust-init.sh"
              chmod +x "rust-init.sh"
              ./rust-init.sh -y --default-toolchain stable --no-modify-path --profile minimal
              export PATH="$HOME/.cargo/bin:$PATH"
              echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
              rustup --version
              cargo --version
              rustc --version
      - run:
          name: Install Deps 
          command: |
            sudo apt install python3-venv python3-pip -y
            pip install maturin
      - run:
          name: Build 
          command: |
            cd src/python_wrapper
            python3 -m venv .env
            source .env/bin/activate
            maturin build
      - store_artifacts:
          path: /root/project/src/python_wrapper/target/wheels/natspec_parser-0.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

workflows:
  python-package:
    jobs:
      - build-the-package