version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          command: |
            sudo apt install python3-pip
            cd src/python_wrapper
            python3 -m venv .env
            source .env/bin/activate
            pip install maturin

workflows:
  python-package:
    jobs:
      - build