version: 2.1
jobs:
  build-wheels:
    docker:
      - image: messense/manylinux2014-cross:x86_64
    steps:
      - checkout
      - run:
          name: "APT Install Dependencies"
          command: |
              sudo apt-get update
              sudo apt-get install curl
      - run:
          name: "Install Rust"
          command: |
              curl "https://sh.rustup.rs" -o "rust-init.sh"
              chmod +x "rust-init.sh"
              ./rust-init.sh -y --default-toolchain stable --no-modify-path --profile minimal
              export PATH="$HOME/.cargo/bin:$PATH"
              echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
              rustup --version
              cargo --version
              rustc --version
      - run:
          name: "Install Maturin and Build Wheels"
          command: |
            for PYBIN in /opt/python/cp3[789]*/bin; do
              "${PYBIN}/pip" install maturin
              "${PYBIN}/maturin" build -m src/python_wrapper/Cargo.toml -i "${PYBIN}/python" --release --manylinux 2014
            done
      - store_artifacts:
          path: /root/project/src/python_wrapper/target/wheels/

workflows:
  python-package:
    jobs:
      - build-wheels