version: 2.1
orbs: 
  python: circleci/python@2.0.3
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo --version
      - run: | 
          cd src/python_wrapper
          python -m venv .env
          source .env/bin/activate
          pip install maturin

workflows:
  python-package:
    jobs:
      - build