version: 2.1
jobs:
  build_macos_wheels:
    docker: 
      - image: cimg/rust:1.
    steps:
      - checkout
      - run 
        name: "display rust versions"
        command: |
          rustup --version
          cargo --version
          rustc --version
      - run
        name: "build  project"
        command: |
           rustup target install x86_64-apple-darwin aarch64-apple-darwin
           pip install maturin
           maturin build --target=aarch64-apple-darwin --universal2
      - store_artifacts:
          path: /root/project/src/python_wrapper/target/wheels/

  build-linux-wheels:
    docker:
      - image: quay.io/pypa/manylinux_2_28_x86_64:latest
    steps:
      - checkout
      - run:
          name: "Install Rust"
          command: |
              yum install curl
              curl "https://sh.rustup.rs" -o "rust-init.sh"
              chmod +x "rust-init.sh"
              ./rust-init.sh -y --default-toolchain stable --no-modify-path --profile minimal
              export PATH="$HOME/.cargo/bin:$PATH"
              echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
              rustup --version
              cargo --version
              rustc --version
      - run:
          name: "Install Maturin and Build Wheels"
          command: |
            for PYBIN in /opt/python/cp3{7,8,9,10,11}*/bin; do
              "${PYBIN}/pip" install maturin
              "${PYBIN}/maturin" build -m src/python_wrapper/Cargo.toml -i "${PYBIN}/python"
            done
      - store_artifacts:
          path: /root/project/src/python_wrapper/target/wheels/

workflows:
  python-package:
    jobs:
      - build-linux-wheels
      - build_macos_wheels