version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Install Deps 
          command: |
            sudo apt install python3-venv python3-pip 
            pip install maturin

      - run:
          name: build 
          command: 
            cd src/python_wrapper
            python3 -m venv .env
            source .env/bin/activate
            maturin build

workflows:
  python-package:
    jobs:
      - build