[package]
name = "python_wrapper"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "natspec_parser"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module", "abi3-py37"] }
natspec_parser = { path = "../.." }
color-eyre = "0.6.2"
indoc = "1.0.6"
itertools = "0.10.3"
lsp-types = "0.93.0"
ropey = "1.5.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
